---
    - shell: curl -s http://localhost:8082
      register: result_82
      ignore_errors: yes

    - shell: curl -s http://localhost:8083
      register: result_83
      ignore_errors: yes

    - name: print result_82 variable
      ansible.builtin.debug:
        var: result_82

    - name: print result_83 variable
      ansible.builtin.debug:
        var: result_83

    - name: Create task6_1 for start
      docker_container:
        name: task6_1
        image: 192.168.1.6:5000/task6:{{my_version}}
        ports:
        - "8082:8080"
      when: result_82.failed and result_83.failed

    - name: Create task6_1
      docker_container:
        name: task6_1
        image: 192.168.1.6:5000/task6:{{my_version}}
        ports:
        - "8082:8080"
      when: result_82.failed and not result_83.failed

    - name: Pause 15 seconds
      pause:
        seconds: 15
      when: result_82.failed and not result_83.failed

    - name: Check 8082
      shell: curl -s http://localhost:8082
      register: result_82_1
      ignore_errors: yes

    - name: print result_82_1 variable
      ansible.builtin.debug:
        var: result_82_1

    - name: Stop task6_2
      docker_container:
        name: task6_2
        state: stopped
        state: absent
      ignore_errors: yes
      when: not result_82_1.failed and not result_83.failed

    - name: Create task6_2
      docker_container:
        name: task6_2
        image: 192.168.1.6:5000/task6:{{my_version}}
        ports:
        - "8083:8080"
      when: result_83.failed and not result_82.failed

    - name: Pause 15 seconds
      pause:
        seconds: 15
      when: result_83.failed and not result_82.failed

    - name: Check 8083
      shell: curl -s http://localhost:8083
      register: result_83_1
      ignore_errors: yes

    - name: print result_83_1 variable
      ansible.builtin.debug:
        var: result_83_1

    - name: Stop task6_1
      docker_container:
        name: task6_1
        state: stopped
        state: absent
      ignore_errors: yes
      when: not result_83_1.failed and not result_82.failed
