version: '2'

services:
  collectd:
    image: fr3nd/collectd
    privileged: true
    network_mode: host
    volumes:
      - /proc:/mnt/proc:ro
      - ./collectd.conf:/etc/collectd/collectd.conf
  influxdb:
    image: influxdb:1.0
    ports:
      - "8083:8083"
      - "8086:8086"
      - "25826:25826/udp"
    volumes:
      - /var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./types.db:/usr/share/collectd/types.db:ro
  grafana:
    image: grafana/grafana:5.1.1
    ports:
      - "3000:3000"
    volumes:
      - /var/lib/grafana
    #  - ./grafana-storage:/home/ilya/var/lib/grafana
    #  - ./docker/grafana/:/etc/grafana/provisioning/datasources/
    #  - ./docker/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
    #  - ./docker/grafana/Dashboard.json:/var/lib/grafana/dashboards/Dashboard.json
