# -*- mode: ruby -*-
# vi: set ft=ruby :
$mach_quant = 2

Vagrant.configure("2") do |config|
  config.vm.define "jenkins" do |subconfig|
    subconfig.vm.box = "minimal/centos7"
    subconfig.vm.box_version = "7.0"
    subconfig.vm.network "private_network", ip: "192.168.1.5"
    subconfig.vm.network "forwarded_port", guest: 8080, host: 8085
    subconfig.vm.provision "shell", path: "./jenkins/jenkins.sh"
    subconfig.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end
  end
 
  config.vm.define "nexus" do |subconfig|
    subconfig.vm.box = "minimal/centos7"
    subconfig.vm.box_version = "7.0"
    subconfig.vm.network "private_network", ip: "192.168.1.6"
    subconfig.vm.network "forwarded_port", guest: 8081, host: 8086
  end
  
end
