---
dependency:
  name: galaxy
driver:
  name: vagrant
lint: |
  yamllint
platforms:
  - name: ubuntu
    box: bento/ubuntu-18.04
    memory: 512
    cpus: 1
provisioner:
  name: ansible
lint: |
  ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../tests/
  options:
    sudo: true
lint: |
  flake8

