version: '3.0'
services:
 elk:
    image: sebp/elk
    ports:
     - "5601:5601"
     - "9200:9200"
     - "5044:5044"
    container_name: opvizor-elk

 filebeat:
    image: docker.elastic.co/beats/filebeat:7.13.2
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: ["--strict.perms=false"] 
