version: '3.2'

services:
  elasticsearch:
    image: elasticsearch:7.13.2
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=docker-cluster
      - network.host=0.0.0.0
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${PASSWORD}
    networks:
      - elk

  logstash:
    image: logstash:7.13.2
    volumes:
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000"
      - "9600:9600"
    expose: 
      - "5044"
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
      - http.host=0.0.0.0
      - xpack.monitoring.elasticsearch.hosts="http://elasticsearch:9200"
      - xpack.monitoring.elasticsearch.username=${LOGIN}
      - xpack.monitoring.elasticsearch.password=${PASSWORD}
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.13.2
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    environment:
      - server.name=kibana
      - server.host=0.0.0.0
      - elasticsearch.hosts="http://elasticsearch:9200"
      - elasticsearch.username=${LOGIN}
      - elasticsearch.password=${PASSWORD}

  filebeat:
    image: store/elastic/filebeat:7.13.2
    entrypoint: "filebeat -e -strict.perms=false"
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./nginx/log:/var/log/nginx/
    networks:
      - elk
    depends_on: 
      - logstash
      - elasticsearch
      - kibana
    links: 
      - logstash

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
