---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint
platforms:
  - name: ubuntu
    image: ubuntu:18.04
    privileged: true
provisioner:
  name: ansible
lint: |
  ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../tests/
  options:
    sudo: true
lint: |
  flake8

